// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efngggxhvigkltophpfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmbmdnZ3hodmlna2x0b3BocGZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDQwODUsImV4cCI6MjA2NTU4MDA4NX0.vEhFif4Bbap_ZBdS1YHlVMLCr9OWnViIgUwgbmh9jD8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);